apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: postgresql
    release: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
  postgres-username: {{ .Values.postgresql.username | b64enc | quote }}
  postgres-database: {{ .Values.postgresql.database | b64enc | quote }}
